name: jbwa
favicon: null
layout_spectrum: 0.6039544357918203
typography_spectrum: 0.12710563093423843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6070535820908844
  lightness: 0.9734704503789544
  saturation: 0.7403332202229649
  rhythmicContrast: 0.3442908769939095
purpose: []
