name: jbwa
favicon: null
layout_spectrum: 0.6039544357918203
typography_spectrum: 0.12710563093423843
title: The SIte
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1791c7'
    - '#ffffff'
    - '#d3eaf4'
    - '#46a7d2'
    - '#a5d4e9'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.7403332202229649
  rhythmicContrast: 0.3442908769939095
purpose: []
